""" Protocols for client and server to communicate between each other.
"""

CONNECT = "CONNECT"
DISCONNECT = "DISCONNECT"
LU = "LU"
LF = "LF"
MESSAGE = "MESSAGE"
READ = "READ"
WRITE = "WRITE"
OVERWRITE = "OVERWRITE"
OVERREAD = "OVERREAD"
APPEND = "APPEND"
APPENDFILE = "APPENDFILE"